[build]
builder = "NIXPACKS"
buildCommand = "pnpm install"

[deploy]
startCommand = "pnpm install && pnpm sequelize-cli db:migrate && pnpm sequelize-cli db:seed:all && pnpm start"

# Servir los archivos estáticos del frontend
[deploy.static]
path = "/"
publicDir = "client"

# Habilitar WebSockets (ya que usas 'ws')
websocket = true

[variables]
NODE_VERSION = "20"