### 🔥 CREAR PEDIDO
POST http://localhost:5001/api/pedidos
Content-Type: application/json

{
  "cliente": {
    "nombre": "Jack",
    "apellido": "Quisiluiza",
    "telefono": "0999999999",
    "email": "jack@test.com",
    "direccion": "Calderon",
    "cedula_ruc": "1717171720"
  },
  "pedido": {
    "direccion_entrega": "Av. 6 de Diciembre 789"
  },
  "detalles": [
    {
      "producto_id": 1,
      "cantidad": 2
    },
    {
      "producto_id": 2,
      "cantidad": 4
    }
  ]
}
### obtener pedido
GET http://localhost:5001/api/pedidos

### obtener pedido especifico
GET http://localhost:5001/api/pedidos/8
### borrar pedido
DELETE http://localhost:5001/api/pedidos/8