### Obtener todos los productos
GET http://localhost:5001/api/productos
Content-Type: application/json


### Obtener producto por ID
GET http://localhost:5001/api/productos/1
Content-Type: application/json


### Crear producto
POST http://localhost:5001/api/productos
Content-Type: application/json

{
  "nombre": "Cheesecake de Fresa",
  "categoria_id": 1,
  "descripcion": "Cheesecake artesanal con topping de fresa",
  "precio": 5.50,
  "imagen": "cheesecake_fresa.jpg",
  "es_nuevo": true,
  "es_popular": false,
  "stock": 20
}


### Actualizar producto
PUT http://localhost:5001/api/productos/2
Content-Type: application/json

{
  "nombre": "Cheesecake de Fresa",
  "categoria_id": 1,
  "descripcion": "Cheesecake artesanal con fresas naturales",
  "precio": 6.00,
  "imagen": "cheesecake_fresa.jpg",
  "es_nuevo": false,
  "es_popular": true,
  "stock": 15
}


### Eliminar producto
DELETE http://localhost:5001/api/productos/2
Content-Type: application/json